Update the descriptions of all procedures and functions based on documentation changes
neo4j/apoc pull request #213
Opened 2022-10-17 07:12 UTC by gem-neo4j

2022-10-20 14:10 UTC, Lojjs requested changes
Thanks for the hard work and a lot of small comment for you! Let me know if we should rather collect all the docs one on a Trello card

2022-10-21 12:11 UTC, gem-neo4j commented on core/src/main/java/apoc/cypher/CypherFunctions.java
> +    @UserFunction("apoc.cypher.runFirstColumnSingle")
hmm I can find it, strange

2022-10-21 14:36 UTC, gem-neo4j commented on core/src/main/java/apoc/nodes/Nodes.java
> +    @Description("Returns all relationships with the given ids.")
ooooh this was a very interesting find. So turns out that the exact same proc is in both Extended and Core. In Core it is actually called apoc.nodes.rels and apoc.get.rels in extended, but I assumed wrongly the other way due to the previous description.

I think I need to go through them all and see if this happens elsewhere so we don't accidentally remove the wrong one :O

2022-10-24 09:14 UTC, Lojjs commented on core/src/main/java/apoc/coll/Coll.java
>      public List<Object> insertAll(@Name("coll") List<Object> coll, @Name("index") long index, @Name("values") List<Object> values) {
Should be fixed in docs as well

2022-10-24 09:16 UTC, Lojjs commented on core/src/main/java/apoc/coll/Coll.java
> +    @Description("Returns whether or not the given value exists in an already sorted collection (using a binary search).")
Should be fixed in docs as well

2022-10-24 09:35 UTC, Lojjs commented on core/src/main/java/apoc/number/Numbers.java
> +  @Description("Formats the given long or double using the given pattern and language to produce a string.")
The 3 changes in this file should be made to docs as well

2022-10-24 12:19 UTC, Lojjs commented on core/src/main/java/apoc/lock/Lock.java
> +    @Procedure(name = "apoc.lock.nodes", mode = Mode.WRITE)
I think this one should be named apoc.lock.rels

2022-10-25 07:44 UTC, Lojjs approved these changes

2022-10-26 07:07 UTC, merged